

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class OperatorInfo : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the OperatorInfo entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public OperatorInfo()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public OperatorInfo(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.OperatorInfo> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.OperatorInfo.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OperatorInfo_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OperatorInfo_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.OperatorInfo.DetailsClass.GetValue(this, global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.OperatorInfo.DetailsClass.SetValue(this, global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.OperatorInfo.DetailsClass.GetValue(this, global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.OperatorInfo.DetailsClass.SetValue(this, global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<short> DBFlag
        {
            get
            {
                return global::LightSwitchApplication.OperatorInfo.DetailsClass.GetValue(this, global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.DBFlag);
            }
            set
            {
                global::LightSwitchApplication.OperatorInfo.DetailsClass.SetValue(this, global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.DBFlag, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DBFlag_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DBFlag_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DBFlag_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreateBy
        {
            get
            {
                return global::LightSwitchApplication.OperatorInfo.DetailsClass.GetValue(this, global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.CreateBy);
            }
            set
            {
                global::LightSwitchApplication.OperatorInfo.DetailsClass.SetValue(this, global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.CreateBy, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime CreateTime
        {
            get
            {
                return global::LightSwitchApplication.OperatorInfo.DetailsClass.GetValue(this, global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.CreateTime);
            }
            set
            {
                global::LightSwitchApplication.OperatorInfo.DetailsClass.SetValue(this, global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.CreateTime, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateTime_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateTime_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateTime_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreateOffice
        {
            get
            {
                return global::LightSwitchApplication.OperatorInfo.DetailsClass.GetValue(this, global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.CreateOffice);
            }
            set
            {
                global::LightSwitchApplication.OperatorInfo.DetailsClass.SetValue(this, global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.CreateOffice, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateOffice_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateOffice_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateOffice_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifyBy
        {
            get
            {
                return global::LightSwitchApplication.OperatorInfo.DetailsClass.GetValue(this, global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.ModifyBy);
            }
            set
            {
                global::LightSwitchApplication.OperatorInfo.DetailsClass.SetValue(this, global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.ModifyBy, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifyBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifyBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifyBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime ModifyTime
        {
            get
            {
                return global::LightSwitchApplication.OperatorInfo.DetailsClass.GetValue(this, global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.ModifyTime);
            }
            set
            {
                global::LightSwitchApplication.OperatorInfo.DetailsClass.SetValue(this, global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.ModifyTime, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifyTime_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifyTime_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifyTime_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifyOffice
        {
            get
            {
                return global::LightSwitchApplication.OperatorInfo.DetailsClass.GetValue(this, global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.ModifyOffice);
            }
            set
            {
                global::LightSwitchApplication.OperatorInfo.DetailsClass.SetValue(this, global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.ModifyOffice, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifyOffice_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifyOffice_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifyOffice_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.WorkSheet WorkSheet
        {
            get
            {
                return global::LightSwitchApplication.OperatorInfo.DetailsClass.GetValue(this, global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.WorkSheet);
            }
            set
            {
                global::LightSwitchApplication.OperatorInfo.DetailsClass.SetValue(this, global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.WorkSheet, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkSheet_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkSheet_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkSheet_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.OperatorInfo,
                global::LightSwitchApplication.OperatorInfo.DetailsClass,
                global::LightSwitchApplication.OperatorInfo.DetailsClass.IImplementation,
                global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass>.Entry
                __OperatorInfoEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass>.Entry(
                    global::LightSwitchApplication.OperatorInfo.DetailsClass.__OperatorInfo_CreateNew,
                    global::LightSwitchApplication.OperatorInfo.DetailsClass.__OperatorInfo_Created,
                    global::LightSwitchApplication.OperatorInfo.DetailsClass.__OperatorInfo_AllowSaveWithErrors);
            private static global::LightSwitchApplication.OperatorInfo __OperatorInfo_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.OperatorInfo> es)
            {
                return new global::LightSwitchApplication.OperatorInfo(es);
            }
            private static void __OperatorInfo_Created(global::LightSwitchApplication.OperatorInfo e)
            {
                e.OperatorInfo_Created();
            }
            private static bool __OperatorInfo_AllowSaveWithErrors(global::LightSwitchApplication.OperatorInfo e)
            {
                bool result = false;
                e.OperatorInfo_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, global::System.Nullable<short>> DBFlag
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.DBFlag) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, global::System.Nullable<short>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, string> CreateBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.CreateBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, global::System.DateTime> CreateTime
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.CreateTime) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, string> CreateOffice
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.CreateOffice) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, string> ModifyBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.ModifyBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, global::System.DateTime> ModifyTime
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.ModifyTime) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, string> ModifyOffice
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.ModifyOffice) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, global::LightSwitchApplication.WorkSheet> WorkSheet
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.WorkSheet) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, global::LightSwitchApplication.WorkSheet>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new global::System.Nullable<short> DBFlag { get; set; }
                new string CreateBy { get; set; }
                new global::System.DateTime CreateTime { get; set; }
                new string CreateOffice { get; set; }
                new string ModifyBy { get; set; }
                new global::System.DateTime ModifyTime { get; set; }
                new string ModifyOffice { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation WorkSheet { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OperatorInfo.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, int>.Data> c, global::LightSwitchApplication.OperatorInfo.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.OperatorInfo e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.OperatorInfo e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.OperatorInfo.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.OperatorInfo.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.OperatorInfo e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OperatorInfo.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.OperatorInfo.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.OperatorInfo e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.OperatorInfo e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.OperatorInfo.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.OperatorInfo.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.OperatorInfo e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, global::System.Nullable<short>>.Entry
                    DBFlag = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, global::System.Nullable<short>>.Entry(
                        "DBFlag",
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._DBFlag_Stub,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._DBFlag_ComputeIsReadOnly,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._DBFlag_Validate,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._DBFlag_GetImplementationValue,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._DBFlag_SetImplementationValue,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._DBFlag_OnValueChanged);
                private static void _DBFlag_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OperatorInfo.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, global::System.Nullable<short>>.Data> c, global::LightSwitchApplication.OperatorInfo.DetailsClass d, object sf)
                {
                    c(d, ref d._DBFlag, sf);
                }
                private static bool _DBFlag_ComputeIsReadOnly(global::LightSwitchApplication.OperatorInfo e)
                {
                    bool result = false;
                    e.DBFlag_IsReadOnly(ref result);
                    return result;
                }
                private static void _DBFlag_Validate(global::LightSwitchApplication.OperatorInfo e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DBFlag_Validate(r);
                }
                private static global::System.Nullable<short> _DBFlag_GetImplementationValue(global::LightSwitchApplication.OperatorInfo.DetailsClass d)
                {
                    return d.ImplementationEntity.DBFlag;
                }
                private static void _DBFlag_SetImplementationValue(global::LightSwitchApplication.OperatorInfo.DetailsClass d, global::System.Nullable<short> v)
                {
                    d.ImplementationEntity.DBFlag = v;
                }
                private static void _DBFlag_OnValueChanged(global::LightSwitchApplication.OperatorInfo e)
                {
                    e.DBFlag_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, string>.Entry
                    CreateBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, string>.Entry(
                        "CreateBy",
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._CreateBy_Stub,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._CreateBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._CreateBy_Validate,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._CreateBy_GetImplementationValue,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._CreateBy_SetImplementationValue,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._CreateBy_OnValueChanged);
                private static void _CreateBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OperatorInfo.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, string>.Data> c, global::LightSwitchApplication.OperatorInfo.DetailsClass d, object sf)
                {
                    c(d, ref d._CreateBy, sf);
                }
                private static bool _CreateBy_ComputeIsReadOnly(global::LightSwitchApplication.OperatorInfo e)
                {
                    bool result = false;
                    e.CreateBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreateBy_Validate(global::LightSwitchApplication.OperatorInfo e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreateBy_Validate(r);
                }
                private static string _CreateBy_GetImplementationValue(global::LightSwitchApplication.OperatorInfo.DetailsClass d)
                {
                    return d.ImplementationEntity.CreateBy;
                }
                private static void _CreateBy_SetImplementationValue(global::LightSwitchApplication.OperatorInfo.DetailsClass d, string v)
                {
                    d.ImplementationEntity.CreateBy = v;
                }
                private static void _CreateBy_OnValueChanged(global::LightSwitchApplication.OperatorInfo e)
                {
                    e.CreateBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, global::System.DateTime>.Entry
                    CreateTime = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, global::System.DateTime>.Entry(
                        "CreateTime",
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._CreateTime_Stub,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._CreateTime_ComputeIsReadOnly,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._CreateTime_Validate,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._CreateTime_GetImplementationValue,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._CreateTime_SetImplementationValue,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._CreateTime_OnValueChanged);
                private static void _CreateTime_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OperatorInfo.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.OperatorInfo.DetailsClass d, object sf)
                {
                    c(d, ref d._CreateTime, sf);
                }
                private static bool _CreateTime_ComputeIsReadOnly(global::LightSwitchApplication.OperatorInfo e)
                {
                    bool result = false;
                    e.CreateTime_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreateTime_Validate(global::LightSwitchApplication.OperatorInfo e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreateTime_Validate(r);
                }
                private static global::System.DateTime _CreateTime_GetImplementationValue(global::LightSwitchApplication.OperatorInfo.DetailsClass d)
                {
                    return d.ImplementationEntity.CreateTime;
                }
                private static void _CreateTime_SetImplementationValue(global::LightSwitchApplication.OperatorInfo.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.CreateTime = global::LightSwitchApplication.OperatorInfo.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _CreateTime_OnValueChanged(global::LightSwitchApplication.OperatorInfo e)
                {
                    e.CreateTime_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, string>.Entry
                    CreateOffice = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, string>.Entry(
                        "CreateOffice",
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._CreateOffice_Stub,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._CreateOffice_ComputeIsReadOnly,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._CreateOffice_Validate,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._CreateOffice_GetImplementationValue,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._CreateOffice_SetImplementationValue,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._CreateOffice_OnValueChanged);
                private static void _CreateOffice_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OperatorInfo.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, string>.Data> c, global::LightSwitchApplication.OperatorInfo.DetailsClass d, object sf)
                {
                    c(d, ref d._CreateOffice, sf);
                }
                private static bool _CreateOffice_ComputeIsReadOnly(global::LightSwitchApplication.OperatorInfo e)
                {
                    bool result = false;
                    e.CreateOffice_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreateOffice_Validate(global::LightSwitchApplication.OperatorInfo e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreateOffice_Validate(r);
                }
                private static string _CreateOffice_GetImplementationValue(global::LightSwitchApplication.OperatorInfo.DetailsClass d)
                {
                    return d.ImplementationEntity.CreateOffice;
                }
                private static void _CreateOffice_SetImplementationValue(global::LightSwitchApplication.OperatorInfo.DetailsClass d, string v)
                {
                    d.ImplementationEntity.CreateOffice = v;
                }
                private static void _CreateOffice_OnValueChanged(global::LightSwitchApplication.OperatorInfo e)
                {
                    e.CreateOffice_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, string>.Entry
                    ModifyBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, string>.Entry(
                        "ModifyBy",
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._ModifyBy_Stub,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._ModifyBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._ModifyBy_Validate,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._ModifyBy_GetImplementationValue,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._ModifyBy_SetImplementationValue,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._ModifyBy_OnValueChanged);
                private static void _ModifyBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OperatorInfo.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, string>.Data> c, global::LightSwitchApplication.OperatorInfo.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifyBy, sf);
                }
                private static bool _ModifyBy_ComputeIsReadOnly(global::LightSwitchApplication.OperatorInfo e)
                {
                    bool result = false;
                    e.ModifyBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifyBy_Validate(global::LightSwitchApplication.OperatorInfo e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifyBy_Validate(r);
                }
                private static string _ModifyBy_GetImplementationValue(global::LightSwitchApplication.OperatorInfo.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifyBy;
                }
                private static void _ModifyBy_SetImplementationValue(global::LightSwitchApplication.OperatorInfo.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ModifyBy = v;
                }
                private static void _ModifyBy_OnValueChanged(global::LightSwitchApplication.OperatorInfo e)
                {
                    e.ModifyBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, global::System.DateTime>.Entry
                    ModifyTime = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, global::System.DateTime>.Entry(
                        "ModifyTime",
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._ModifyTime_Stub,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._ModifyTime_ComputeIsReadOnly,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._ModifyTime_Validate,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._ModifyTime_GetImplementationValue,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._ModifyTime_SetImplementationValue,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._ModifyTime_OnValueChanged);
                private static void _ModifyTime_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OperatorInfo.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.OperatorInfo.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifyTime, sf);
                }
                private static bool _ModifyTime_ComputeIsReadOnly(global::LightSwitchApplication.OperatorInfo e)
                {
                    bool result = false;
                    e.ModifyTime_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifyTime_Validate(global::LightSwitchApplication.OperatorInfo e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifyTime_Validate(r);
                }
                private static global::System.DateTime _ModifyTime_GetImplementationValue(global::LightSwitchApplication.OperatorInfo.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifyTime;
                }
                private static void _ModifyTime_SetImplementationValue(global::LightSwitchApplication.OperatorInfo.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.ModifyTime = global::LightSwitchApplication.OperatorInfo.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _ModifyTime_OnValueChanged(global::LightSwitchApplication.OperatorInfo e)
                {
                    e.ModifyTime_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, string>.Entry
                    ModifyOffice = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, string>.Entry(
                        "ModifyOffice",
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._ModifyOffice_Stub,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._ModifyOffice_ComputeIsReadOnly,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._ModifyOffice_Validate,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._ModifyOffice_GetImplementationValue,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._ModifyOffice_SetImplementationValue,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._ModifyOffice_OnValueChanged);
                private static void _ModifyOffice_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OperatorInfo.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, string>.Data> c, global::LightSwitchApplication.OperatorInfo.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifyOffice, sf);
                }
                private static bool _ModifyOffice_ComputeIsReadOnly(global::LightSwitchApplication.OperatorInfo e)
                {
                    bool result = false;
                    e.ModifyOffice_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifyOffice_Validate(global::LightSwitchApplication.OperatorInfo e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifyOffice_Validate(r);
                }
                private static string _ModifyOffice_GetImplementationValue(global::LightSwitchApplication.OperatorInfo.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifyOffice;
                }
                private static void _ModifyOffice_SetImplementationValue(global::LightSwitchApplication.OperatorInfo.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ModifyOffice = v;
                }
                private static void _ModifyOffice_OnValueChanged(global::LightSwitchApplication.OperatorInfo e)
                {
                    e.ModifyOffice_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, global::LightSwitchApplication.WorkSheet>.Entry
                    WorkSheet = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, global::LightSwitchApplication.WorkSheet>.Entry(
                        "WorkSheet",
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._WorkSheet_Stub,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._WorkSheet_ComputeIsReadOnly,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._WorkSheet_Validate,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._WorkSheet_GetCoreImplementationValue,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._WorkSheet_GetImplementationValue,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._WorkSheet_SetImplementationValue,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._WorkSheet_Refresh,
                        global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties._WorkSheet_OnValueChanged);
                private static void _WorkSheet_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OperatorInfo.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, global::LightSwitchApplication.WorkSheet>.Data> c, global::LightSwitchApplication.OperatorInfo.DetailsClass d, object sf)
                {
                    c(d, ref d._WorkSheet, sf);
                }
                private static bool _WorkSheet_ComputeIsReadOnly(global::LightSwitchApplication.OperatorInfo e)
                {
                    bool result = false;
                    e.WorkSheet_IsReadOnly(ref result);
                    return result;
                }
                private static void _WorkSheet_Validate(global::LightSwitchApplication.OperatorInfo e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.WorkSheet_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _WorkSheet_GetCoreImplementationValue(global::LightSwitchApplication.OperatorInfo.DetailsClass d)
                {
                    return d.ImplementationEntity.WorkSheet;
                }
                private static global::LightSwitchApplication.WorkSheet _WorkSheet_GetImplementationValue(global::LightSwitchApplication.OperatorInfo.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.WorkSheet, global::LightSwitchApplication.WorkSheet.DetailsClass>(global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.WorkSheet, ref d._WorkSheet);
                }
                private static void _WorkSheet_SetImplementationValue(global::LightSwitchApplication.OperatorInfo.DetailsClass d, global::LightSwitchApplication.WorkSheet v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.WorkSheet, ref d._WorkSheet, (i, ev) => i.WorkSheet = ev, v);
                }
                private static void _WorkSheet_Refresh(global::LightSwitchApplication.OperatorInfo.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.OperatorInfo.DetailsClass.PropertySetProperties.WorkSheet, ref d._WorkSheet);
                }
                private static void _WorkSheet_OnValueChanged(global::LightSwitchApplication.OperatorInfo e)
                {
                    e.WorkSheet_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, global::System.Nullable<short>>.Data _DBFlag;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, string>.Data _CreateBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, global::System.DateTime>.Data _CreateTime;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, string>.Data _CreateOffice;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, string>.Data _ModifyBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, global::System.DateTime>.Data _ModifyTime;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, string>.Data _ModifyOffice;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.OperatorInfo, global::LightSwitchApplication.OperatorInfo.DetailsClass, global::LightSwitchApplication.WorkSheet>.Data _WorkSheet;
            
        }
    
        #endregion
    }
    
    #endregion
}
