//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class WorkSheetsListDetail
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private WorkSheetsListDetail() : base("LightSwitchApplication:WorkSheetsListDetail")
        {
            global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static WorkSheetsListDetail CreateInstance()
        {
            return new global::LightSwitchApplication.WorkSheetsListDetail(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkSheetsListDetail_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkSheetsListDetail_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkSheetsListDetail_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkSheetsListDetail_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkSheetsListDetail_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkSheetsListDetail_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkSheetsListDetail_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void WorkSheets_SelectionChanged();

        partial void WorkSheets_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkSheets_Loaded(bool succeeded);

        partial void Callers_SelectionChanged();

        partial void Callers_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Callers_Loaded(bool succeeded);

        partial void OperatorInfoes_SelectionChanged();

        partial void OperatorInfoes_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OperatorInfoes_Loaded(bool succeeded);

        partial void Defendants_SelectionChanged();

        partial void Defendants_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Defendants_Loaded(bool succeeded);

        partial void BondNotes_SelectionChanged();

        partial void BondNotes_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BondNotes_Loaded(bool succeeded);

        /// <summary>
        /// Gets the WorkSheets visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.WorkSheet> WorkSheets
        {
            get
            {
                return global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties.WorkSheets);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkSheets_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the Callers visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Caller> Callers
        {
            get
            {
                return global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties.Callers);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Callers_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the OperatorInfoes visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.OperatorInfo> OperatorInfoes
        {
            get
            {
                return global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties.OperatorInfoes);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OperatorInfoes_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the Defendants visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Defendant> Defendants
        {
            get
            {
                return global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties.Defendants);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Defendants_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the BondNotes visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.BondNote> BondNotes
        {
            get
            {
                return global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties.BondNotes);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BondNotes_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySet, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.CommandSet, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties.WorkSheets;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass>.Entry
                __WorkSheetsListDetailEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass>.Entry(
                    global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.__WorkSheetsListDetail_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.__WorkSheetsListDetail_InvokeSavingEvent,
                    global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.__WorkSheetsListDetail_InvokeSavedEvent,
                    global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.__WorkSheetsListDetail_InvokeClosingEvent,
                    global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.__WorkSheetsListDetail_InvokeCreated,
                    global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.__WorkSheetsListDetail_InvokeActivated,
                    global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.__WorkSheetsListDetail_InvokeSaveErrorEvent);
            private static void __WorkSheetsListDetail_InvokeInitializeDataWorkspace(global::LightSwitchApplication.WorkSheetsListDetail s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.WorkSheetsListDetail_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __WorkSheetsListDetail_InvokeSavingEvent(global::LightSwitchApplication.WorkSheetsListDetail s)
            {
                bool handled = false;
                s.WorkSheetsListDetail_Saving(ref handled);
                return handled;
            }
            private static void __WorkSheetsListDetail_InvokeSavedEvent(global::LightSwitchApplication.WorkSheetsListDetail s)
            {
                s.WorkSheetsListDetail_Saved();
            }
            private static bool __WorkSheetsListDetail_InvokeClosingEvent(global::LightSwitchApplication.WorkSheetsListDetail s)
            {
                bool cancel = false;
                s.WorkSheetsListDetail_Closing(ref cancel);
                return cancel;
            }
            private static void __WorkSheetsListDetail_InvokeCreated(global::LightSwitchApplication.WorkSheetsListDetail s)
            {
                s.WorkSheetsListDetail_Created();
            }
            private static void __WorkSheetsListDetail_InvokeActivated(global::LightSwitchApplication.WorkSheetsListDetail s)
            {
                s.WorkSheetsListDetail_Activated();
            }
            private static bool __WorkSheetsListDetail_InvokeSaveErrorEvent(global::LightSwitchApplication.WorkSheetsListDetail s, global::System.Exception ex)
            {
                bool handled = false;
                s.WorkSheetsListDetail_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable WorkSheetsQuery()
            {
                return this.Screen.DataWorkspace.ApplicationData.WorkSheets;
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable CallersQuery()
            {
                if (this.Screen.WorkSheets.SelectedItem == null)
                {
                    return null;
                }

                global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Caller> loader =
                    (global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Caller>)((global::Microsoft.LightSwitch.Details.ILoadableProperty)this.Screen.WorkSheets.SelectedItem.Details.Properties.Callers).Loader;
                if (loader == null)
                {
                    return null;
                }

                return loader;
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable OperatorInfoesQuery()
            {
                if (this.Screen.WorkSheets.SelectedItem == null)
                {
                    return null;
                }

                global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.OperatorInfo> loader =
                    (global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.OperatorInfo>)((global::Microsoft.LightSwitch.Details.ILoadableProperty)this.Screen.WorkSheets.SelectedItem.Details.Properties.OperatorInfoes).Loader;
                if (loader == null)
                {
                    return null;
                }

                return loader;
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable DefendantsQuery()
            {
                if (this.Screen.WorkSheets.SelectedItem == null)
                {
                    return null;
                }

                global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Defendant> loader =
                    (global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Defendant>)((global::Microsoft.LightSwitch.Details.ILoadableProperty)this.Screen.WorkSheets.SelectedItem.Details.Properties.Defendants).Loader;
                if (loader == null)
                {
                    return null;
                }

                return loader;
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable BondNotesQuery()
            {
                if (this.Screen.WorkSheets.SelectedItem == null)
                {
                    return null;
                }

                global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.BondNote> loader =
                    (global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.BondNote>)((global::Microsoft.LightSwitch.Details.ILoadableProperty)this.Screen.WorkSheets.SelectedItem.Details.Properties.BondNotes).Loader;
                if (loader == null)
                {
                    return null;
                }

                return loader;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.WorkSheet>.Data _WorkSheets;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.Caller>.Data _Callers;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.OperatorInfo>.Data _OperatorInfoes;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.Defendant>.Data _Defendants;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.BondNote>.Data _BondNotes;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.WorkSheet> WorkSheets
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.WorkSheet>)base.GetItem(global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties.WorkSheets);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.Caller> Callers
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.Caller>)base.GetItem(global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties.Callers);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.OperatorInfo> OperatorInfoes
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.OperatorInfo>)base.GetItem(global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties.OperatorInfoes);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.Defendant> Defendants
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.Defendant>)base.GetItem(global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties.Defendants);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.BondNote> BondNotes
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.BondNote>)base.GetItem(global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties.BondNotes);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.WorkSheet>.Entry
                    WorkSheets = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.WorkSheet>.Entry(
                        "WorkSheets",
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._WorkSheets_Stub,
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._WorkSheets_Validate,
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._WorkSheets_CreateQuery,
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._WorkSheets_SelectionChanged,
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._WorkSheets_OnCollectionChanged,
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._WorkSheets_OnLoaded);
                private static void _WorkSheets_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.WorkSheet>.Data> c, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._WorkSheets, sf);
                }
                private static void _WorkSheets_Validate(global::LightSwitchApplication.WorkSheetsListDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.WorkSheets_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _WorkSheets_CreateQuery(global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass d, object[] args)
                {
                    return d.WorkSheetsQuery();
                }
                private static void _WorkSheets_SelectionChanged(global::LightSwitchApplication.WorkSheetsListDetail s)
                {
                    s.WorkSheets_SelectionChanged();
                }
                private static void _WorkSheets_OnCollectionChanged(global::LightSwitchApplication.WorkSheetsListDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.WorkSheets_Changed(e);
                }
                private static void _WorkSheets_OnLoaded(global::LightSwitchApplication.WorkSheetsListDetail s, bool succeeded)
                {
                    s.WorkSheets_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.Caller>.Entry
                    Callers = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.Caller>.Entry(
                        "Callers",
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._Callers_Stub,
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._Callers_Validate,
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._Callers_CreateQuery,
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._Callers_SelectionChanged,
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._Callers_OnCollectionChanged,
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._Callers_OnLoaded);
                private static void _Callers_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.Caller>.Data> c, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Callers, sf);
                }
                private static void _Callers_Validate(global::LightSwitchApplication.WorkSheetsListDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Callers_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Callers_CreateQuery(global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass d, object[] args)
                {
                    return d.CallersQuery();
                }
                private static void _Callers_SelectionChanged(global::LightSwitchApplication.WorkSheetsListDetail s)
                {
                    s.Callers_SelectionChanged();
                }
                private static void _Callers_OnCollectionChanged(global::LightSwitchApplication.WorkSheetsListDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Callers_Changed(e);
                }
                private static void _Callers_OnLoaded(global::LightSwitchApplication.WorkSheetsListDetail s, bool succeeded)
                {
                    s.Callers_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.OperatorInfo>.Entry
                    OperatorInfoes = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.OperatorInfo>.Entry(
                        "OperatorInfoes",
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._OperatorInfoes_Stub,
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._OperatorInfoes_Validate,
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._OperatorInfoes_CreateQuery,
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._OperatorInfoes_SelectionChanged,
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._OperatorInfoes_OnCollectionChanged,
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._OperatorInfoes_OnLoaded);
                private static void _OperatorInfoes_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.OperatorInfo>.Data> c, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._OperatorInfoes, sf);
                }
                private static void _OperatorInfoes_Validate(global::LightSwitchApplication.WorkSheetsListDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.OperatorInfoes_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _OperatorInfoes_CreateQuery(global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass d, object[] args)
                {
                    return d.OperatorInfoesQuery();
                }
                private static void _OperatorInfoes_SelectionChanged(global::LightSwitchApplication.WorkSheetsListDetail s)
                {
                    s.OperatorInfoes_SelectionChanged();
                }
                private static void _OperatorInfoes_OnCollectionChanged(global::LightSwitchApplication.WorkSheetsListDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.OperatorInfoes_Changed(e);
                }
                private static void _OperatorInfoes_OnLoaded(global::LightSwitchApplication.WorkSheetsListDetail s, bool succeeded)
                {
                    s.OperatorInfoes_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.Defendant>.Entry
                    Defendants = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.Defendant>.Entry(
                        "Defendants",
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._Defendants_Stub,
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._Defendants_Validate,
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._Defendants_CreateQuery,
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._Defendants_SelectionChanged,
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._Defendants_OnCollectionChanged,
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._Defendants_OnLoaded);
                private static void _Defendants_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.Defendant>.Data> c, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Defendants, sf);
                }
                private static void _Defendants_Validate(global::LightSwitchApplication.WorkSheetsListDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Defendants_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Defendants_CreateQuery(global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass d, object[] args)
                {
                    return d.DefendantsQuery();
                }
                private static void _Defendants_SelectionChanged(global::LightSwitchApplication.WorkSheetsListDetail s)
                {
                    s.Defendants_SelectionChanged();
                }
                private static void _Defendants_OnCollectionChanged(global::LightSwitchApplication.WorkSheetsListDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Defendants_Changed(e);
                }
                private static void _Defendants_OnLoaded(global::LightSwitchApplication.WorkSheetsListDetail s, bool succeeded)
                {
                    s.Defendants_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.BondNote>.Entry
                    BondNotes = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.BondNote>.Entry(
                        "BondNotes",
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._BondNotes_Stub,
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._BondNotes_Validate,
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._BondNotes_CreateQuery,
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._BondNotes_SelectionChanged,
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._BondNotes_OnCollectionChanged,
                        global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass.PropertySetProperties._BondNotes_OnLoaded);
                private static void _BondNotes_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkSheetsListDetail, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass, global::LightSwitchApplication.BondNote>.Data> c, global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._BondNotes, sf);
                }
                private static void _BondNotes_Validate(global::LightSwitchApplication.WorkSheetsListDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.BondNotes_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _BondNotes_CreateQuery(global::LightSwitchApplication.WorkSheetsListDetail.DetailsClass d, object[] args)
                {
                    return d.BondNotesQuery();
                }
                private static void _BondNotes_SelectionChanged(global::LightSwitchApplication.WorkSheetsListDetail s)
                {
                    s.BondNotes_SelectionChanged();
                }
                private static void _BondNotes_OnCollectionChanged(global::LightSwitchApplication.WorkSheetsListDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.BondNotes_Changed(e);
                }
                private static void _BondNotes_OnLoaded(global::LightSwitchApplication.WorkSheetsListDetail s, bool succeeded)
                {
                    s.BondNotes_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
}
